### ISSUE TITLE
Documentation on rust-analyzer seems outdated / anything to improve integration?

### ISSUE THREAD

**Issue by bluenote10** [godot-rust/gdnative-book#57]
The section [How do I get auto-completion with rust-analyzer?](https://godot-rust.github.io/book/faq/configuration.html#how-do-i-get-auto-completion-with-rust-analyzer) seems outdated, because [`rust-analyzer.cargo.loadOutDirsFromCheck` no longer exists](https://github.com/rust-analyzer/rust-analyzer/issues/6448#issuecomment-961403175).

In practice this is impacting my productivity quite a lot, because auto-completion within a native class exported function doesn't seem to work at all. Often, my IDE is in a state reporting simply "all broken"

![image](https://user-images.githubusercontent.com/3620703/143691057-fe1b00a1-c569-40ad-aa52-b5fc8d11dca5.png)

... and if this happens when I'm having a weak moment it can take a while to spot the actual error.

To avoid getting impacted by this issue I have now started to implement more complex methods as free floating functions like
```rust
fn process(this: &mut MyClass, delta: f64) -> Option<()> {
    // ...
}
```
and forward calls from the methods, which is of course unnecessary boilerplate.

------

To narrow down the problem we probably need to answer the questions:

1. Is this just something broken with my setup, or is everyone using rust-analyzer facing these issues?

2. If it is setup related, what are the tricks to get it going, which we could update in the book?

3. If it turns out that it is fundamentally not working, the question may be if we can do something on library / macro side to improve it. Following [the links posted](https://github.com/rust-analyzer/rust-analyzer/issues/6448#issuecomment-961441435) by the rust-analyzer maintainer leads to a [similar issue](https://github.com/rust-analyzer/rust-analyzer/issues/10520) for `tokio-tracing`, caused by the usage of `syn` and [this proposal](https://github.com/tokio-rs/tracing/issues/1633) to solve it on their side. @Bromeon Is this proposal applicable to godot-rust as well?

**Comment by jacobsky** [comment]
@bluenote10 I agree, that part of the FAQ appears to be outdated. Thanks for creating the issue!

I have noticed similar issues occurring with the recent changes to Rust Analyzer, a lot of the issues appear to be related to rust-analyzer's macro expansion, so I ended up disabling them for the time being. I haven't noticed too many issues with rust analyzer though. It would be good to see what other folks using Rust Analyzer experience as well.

**Comment by Bromeon** [comment]
Does anyone who uses Rust-Analyzer have time to investigate this issue?
I can't say much about it as I'm on CLion.

> 3\. If it turns out that it is fundamentally not working, the question may be if we can do something on library / macro side to improve it. Following [the links posted](https://github.com/rust-analyzer/rust-analyzer/issues/6448#issuecomment-961441435) by the rust-analyzer maintainer leads to a [similar issue](https://github.com/rust-analyzer/rust-analyzer/issues/10520) for `tokio-tracing`, caused by the usage of `syn` and [this proposal](https://github.com/tokio-rs/tracing/issues/1633) to solve it on their side. @Bromeon Is this proposal applicable to godot-rust as well?

You mean design the macros in a way that they don't fail hard but allow to handle the error? Maybe, but if `syn` suffers from the same issue, it wouldn't help if we fixed anything on godot-rust side, would it?

**Comment by jacobsky** [comment]
@Bromeon I'm using Rust Analyzer, I'll doublecheck to see if there are any issues with a default install. It's been a while since I checked on my end.

**Comment by bluenote10** [comment]
It should be noted that this big related tracking issue on rust-analyzer side https://github.com/rust-lang/rust-analyzer/issues/11014 has been closed recently, so perhaps things are much better in the meantime (hope I can re-check as well soon).

**Comment by jacobsky** [comment]
I re-checked this issue with default settings from Rust Analyzer and it doesn't seem to be impacting anything on my end anymore. @bluenote10 please feel free to re-open this issue if you see any issues.

**Comment by bluenote10** [comment]
@jacobsky I finally had some time to experiment with more recent rust-analyzer versions, and it looks like the issue with everything being underlined in red is indeed gone now.

What still isn't working for me is if you have e.g. `use gdnative::prelude::Object;` and you ctrl-click on `Object`. In this case I always end up here:

![image](https://user-images.githubusercontent.com/3620703/206723944-b97e14c4-6309-4c58-b1dc-2399bd0eba17.png)

Do you get redirected to the actual implementation?

**Comment by Bromeon** [comment]
Reopen until clarified.
